---
- name: Playbook for JDG Hosts
  hosts: datagrid
  become: yes
  roles:
    - role: redhat.data_grid.data_grid
      data_grid_users: "{{ user_accounts }}"
      data_grid_supervisor_password: "{{ admin_pass }}"
  pre_tasks:
    - name: Configure promtail
      ansible.builtin.include_role:
        name: promtail
      vars:
        promtail_job_name: datagrid
        promtail_logfile: /var/log/data_grid/server.log
        promtail_region: "{{ hostvars[inventory_hostname].tags.Region }}"
