---
- name: Playbook for rhsso Hosts
  hosts: rhbk
  roles:
    - role: redhat.rhbk.rhbk
      rhbk_admin_pass: "{{ admin_pass }}"
  pre_tasks:
    - name: Configure promtail
      ansible.builtin.include_role:
        name: promtail
      when: not skip_promtail is defined
      vars:
        promtail_job_name: rhbk
        promtail_logfile: /var/log/sso/server.log
        promtail_region: "{{ hostvars[inventory_hostname].tags.Region }}"
  post_tasks:
    - include_role:
        name: redhat.rhbk.rhbk_realm
        apply:
          delegate_to: "{{ ansible_play_hosts | first }}"
          run_once: true
      vars:
        rhbk_admin_password: "{{ admin_pass }}"
        rhbk_context: ''
        rhbk_realm: addressbook
        rhbk_clients:
          - name: addressbook
            client_id: addressbook
            roles:
              - flangeadmin
              - flangeuser
            realm: addressbook
            public_client: true
            web_origins: '+'
            users:
              - username: flangeadmin
                email: ansible-middleware-core@redhat.com
                firstName: Flange
                lastName: Admin
                password: password
                client_roles:
                  - client: addressbook
                    role: flangeadmin
                    realm: addressbook
                  - client: addressbook
                    role: flangeuser
                    realm: addressbook
              - username: flangeuser
                email: ggraziol@redhat.com
                firstName: Flange
                lastName: User
                password: password
                client_roles:
                  - client: addressbook
                    role: flangeuser
                    realm: addressbook
