---
sso_ha_enabled: True
sso_frontend_url: "https://{{ external_domain_name }}/auth/"
sso_jdbc_engine: mariadb
sso_jdbc_url: "{{ site_jdbc_url }}/keycloak?socketTimeout=10000"

sso_db_user: keycloak-user
sso_db_pass: keycloak-pass
sso_configure_firewalld: True
sso_offline_install: False
sso_management_port_bind_address: 0.0.0.0
sso_db_background_validate_on_match: True
sso_db_valid_conn_sql: 'SELECT 1'
admin_pass: "redhat1!but12long"

sso_infinispan_user: rhsso
sso_infinispan_pass: rhssopassword
sso_infinispan_use_ssl: True
sso_infinispan_url: "{{ data_grid_jgroups_relay_site }}-datagrid1{{ domain_name }}"